stamp:
  user:
  time:
  experiment_name:


data:
  dataloader:
    train:
      batch_size: 1
      num_workers: 1
      shuffle: true
    valid:
      batch_size: 1
      num_workers: 4
      shuffle: true
    test:
      batch_size: 1
      num_workers: 4
      shuffle: true

  dataset:
    defaults: &defaults
      root_path: '/home/ys/Data/ILSVRC'
      data_path: 'Data/VID/train'
      annotation_path: 'Annotations/VID/train'

    train:
      <<: *defaults

    valid:
      <<: *defaults

tracker:
  windowing: 'cosine'

  total_stride: 8
  context_amount: 0.5  # context amount for the exemplar
  ratios: [0.33, 0.5, 1, 2, 3]
  scales: [8, ]
  anchor: []
  penalty_k: 0.055
  window_influence: 0.42
  lr: 0.295

model:
  z_size: 127
  u_size: 255
  res_size: 17
  anchor_num: 5

loss:
  1

optim:
  lr: !!float 1e-6
  weight_decay: !!float 1e-5

train:
  epochs: 10000
  log_interval: 10
  save_model_epoch_interval: 10
  valid_interval: 1

save:
  root_: '/home/ys/Data/pose_estimate_save/'
  root:
  relative_model: 'models'
  relative_train: 'train'
  relative_valid: 'valid'
  relative_analyze: 'valid/coco_analyze'
  relative_tensorboard: 'tensorboard'
  relative_test: 'tst'
  model:
  train:
  valid:
  analyze:
  tensorboard:
  test:

device: 'cuda'
device_ids: [0]

tensorboard:
  enable: true

visdom:
  enable: false
